FROM python:3.11-slim

RUN apt-get update && apt-get install -y --no-install-recommends \
    curl \
    libgomp1 \
    && rm -rf /var/lib/apt/lists/*

ENV PYTHONUNBUFFERED=1
ARG WHEEL_URL="https://abetlen.github.io/llama-cpp-python/whl/cpu"

RUN pip install --no-cache-dir requests
RUN pip install --no-cache-dir llama-cpp-python --extra-index-url ${WHEEL_URL} --only-binary=llama-cpp-python

COPY src /app/src
WORKDIR /app

CMD ["python", "-m", "src.nodes.worker"]
